### ISSUE TITLE
How to retrieve a specific object?

### ISSUE THREAD

**Issue by expelliamus** [alexnzarov/telegraf-session-mongodb#6]
Hi,

I'm using your library for a persistent session and is working really well. Anyway, I would ask a question, I need to get a specific object in the `sessions` document eh: `__language_code` (i18n Middleware object). At the moment I did:

    const { TelegrafMongoSession } = require('telegraf-session-mongodb');
    const Telegraf = require('telegraf');
    const bot = new Telegraf(process.env.TOKEN);
 
    TelegrafMongoSession.setup(bot, process.ENV.MONGODB_URI)
  .then((client) => bot.launch())
  .catch((err) => console.log(`Failed to connect to the database: ${err}`));

Is there a way to access to the session stored objects/values using the session instance? How?

Kind regards

**Comment by olexnzarov** [comment]
Hey.

TelegrafMongoSession.setup returns a Promise that resolves to the MongoClient object. You can use this object to find anything you want in the connected database, like this:

```js

TelegrafMongoSession.setup(bot, process.ENV.MONGODB_URI)
  .then(client => {
    const db = client.db();
    const sessions = db.collection('sessions');
    
    // do whatever you need with the sessions collection
  });

```

**Comment by sfanculatodinotte** [comment]
Hi, thanks for the reply, when I use your code above I get:

>

**Comment by sfanculatodinotte** [comment]
Hi @alexnzarov , thanks for the answer, I just want ask another question:

your code return all the sessions stored? or just the session of user that's running the application? 'cause I need to access to only the details of the session of the current user. Eg, suppose I have the following sessions details:

<img src="https://i.stack.imgur.com/Q5YTm.jpg">

how can I return "__language_code"?

**Comment by olexnzarov** [comment]
It would be something like this:
```js
  const { data: { __language_code } } = await sessions.findOne({ key: `${userId}:${userId}` });
```
But if you have a context it's much easier:
```js
  const { session: { __language_code } } = ctx;
```
